service: first-app

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    LOCAL: HOTMART
    GUEST: DEV_IN_COMPANY
    
stage: dev
region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
